<section class="admin__page-section edit-howtorefund">
    <div class="howtorefund-block-title">
        <h2><?php echo __('BACKEND_TT_HOWTO_FULLREFUND'); ?></h2>
    </div>
    <div class="howtorefund-block-item">
        <ol type="1">
            <li><?php echo __('BACKEND_TT_REFUND_MENU_ORDER'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_TRANSACTION'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_MENU_INVOICE'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_INVOICE_DATA'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_MENU_CREDITMEMO'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_FINISH'); ?></li>
        </ol>
    </div>
    <div class="howtorefund-separator"/>
    <div class="howtorefund-block-title">
        <h2><?php echo __('BACKEND_TT_HOWTO_PARTIALREFUND'); ?></h2>
    </div>
    <div class="howtorefund-block-item">
        <ol type="1">
            <li><?php echo __('BACKEND_TT_REFUND_MENU_ORDER'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_TRANSACTION'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_MENU_INVOICE'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_INVOICE_DATA'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_MENU_CREDITMEMO'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_PARTIAL_QTY'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_PARTIAL_QTY_UPDATE'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_PARTIAL_ADJUSTMENT'); ?></li>
            <li><?php echo __('BACKEND_TT_REFUND_FINISH'); ?></li>
        </ol>
    </div>
</section>
